Allow passing of axios_config
LuanRT/google-this pull request #29
Opened 2022-07-29 17:02 UTC by gregpriday

## Description

This PR is fairly simple. It just gives you the ability to pass extra `axios_config` in the `options` parameter. The 

It Fixes https://github.com/LuanRT/google-this/issues/21 by allowing you to pass proxy servers.

```javascript
import SocksProxyAgent from 'socks-proxy-agent';

const httpsAgent = new SocksProxyAgent.SocksProxyAgent(...);
const options = {
  page: 0,
  safe: false,
  additional_params: {
    hl: 'en'
  },
  axios_config: {
    timeout: 15000,
    proxy: false,
    httpsAgent: httpsAgent
  }
}

const response = await google.search('how do you scrape google results?', options);
```

It should support standard HTTPS proxies, too. I just generally use Socks5.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2022-07-29 17:04 UTC, gregpriday commented
If this looks good, I'll finish other items on the checklist. Adding tests and documentation. It's a minor change though.

2022-07-31 01:45 UTC, LuanRT commented
Sweet! And yup I agree, you don't have to add tests for this particular change. Left a review.

Thanks again!

2022-07-31 01:46 UTC, LuanRT requested changes

2022-07-31 01:46 UTC, LuanRT commented on lib/core/main.js
> +  const response = await Axios.get(url, { headers: Utils.getHeaders({ mobile: true }), ...options.axios_config }).catch((err) => err);
The `options` param doesn't exist in this function though, other than that everything looks good!

2022-09-04 03:57 UTC, closed without merging